[tool.poetry]
name = "keras-edge"
version = "0.1.0"
description = ""
authors = ["Adam Page <apage224@gmail.com>"]
readme = "README.md"
packages = [
    { include = "keras_edge" },
]

[tool.poetry.dependencies]
python = "^3.11"
h5py = "^3.10.0"
keras = "^3.0.4"
pydantic = "^2.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
